sass:
  sass_dir: assets/css
  ## prod
  style: compressed
  ## debug
  # sourcemap: development
  # style: expanded

plugins:
  # ... also change in `Gemfile`
  - jekyll-sitemap

include:
  - '.htaccess'
  - 'sitemap.xsl'

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .sass-cache/
  - _compress_images_cache.yml
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - conf/
  - .npmrc
  - node_modules/
  - package.json
  - package-lock.json
  - _plugins/
  - _build/
  - _data.examples
  - .browserslistrc
